# Generated by Django 4.2.7 on 2025-12-01 06:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio del paquete (ej: para 2x20$, precio=20). Solo para tipo 'buy_x_for_price'", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='offer',
            name='quantity_x',
            field=models.PositiveIntegerField(default=1, help_text="Cantidad X (ej: para 2x1, X=2). Solo para tipos 'buy_x_get_y' y 'buy_x_for_price'"),
        ),
        migrations.AddField(
            model_name='offer',
            name='quantity_y',
            field=models.PositiveIntegerField(blank=True, default=1, help_text="Cantidad Y (ej: para 2x1, Y=1). Solo para tipo 'buy_x_get_y'", null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Cantidad Fija'), ('buy_x_get_y', 'Compra X Lleva Y (ej: 2x1)'), ('buy_x_for_price', 'Compra X por Precio (ej: 2x20$)')], default='percentage', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Solo para tipos 'percentage' y 'fixed'", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
