# Generated by Django 4.2.7 on 2025-12-01 06:08

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_offer_bundle_price_offer_quantity_x_offer_quantity_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Precio unitario original. Opcional para ofertas tipo 'buy_x_for_price' (aplica a todo el menú)", max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
